package transport;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import java.awt.Font;
import javax.swing.JTextPane;

/**
 *
 * @author 
 */
public class Loginsignup extends javax.swing.JFrame {

    /**
     * Creates new formLoginsignup
     */
    
    int posX;
    int posY;
    
    public Loginsignup() {
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
        this.setBackground(new Color(255, 255, 255, 0));
        inpUsername.setBackground(new Color(255, 255, 255, 0));
        inpPassword.setBackground(new Color(255, 255, 255, 0));
        inpUsername.setText("");
        inpPassword.setText("");
        
        btnNewButton_2 = new JButton("Login");
        btnNewButton_2.setBounds(593, 532, 207, 79);
        getContentPane().add(btnNewButton_2);
        this.addMouseListener(new MouseAdapter() {
            public void mousePressed(MouseEvent e) {
            	String username=inpUsername.getText();
                String password=inpPassword.getText();
                new user(username,password);
                posX = e.getX();
                posY = e.getY();
                setVisible(false);
            }
        });
        this.addMouseMotionListener(new MouseAdapter() {
            public void mouseDragged(MouseEvent evt) {
                //sets frame position when mouse dragged			
                setLocation(evt.getXOnScreen() , evt.getYOnScreen());

            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        btnSignUp = new javax.swing.JLabel();
        btnSignUp.setBackground(Color.LIGHT_GRAY);
        inpUsername = new javax.swing.JTextField();
        inpPassword = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        rightPanel = new javax.swing.JLabel();
        rightPanel.setIcon(new ImageIcon("D:\\java\\transport\\images\\images\\litegreen.jpg"));
        leftPanel = new javax.swing.JLabel();
        leftPanel.setIcon(new ImageIcon("D:\\java\\transport\\images\\images\\LeftPanelBackGround (1).jpg"));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(900, 650));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(900, 650));
        getContentPane().setLayout(null);

        jLabel10.setFont(new Font("Berlin Sans FB", Font.PLAIN, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Password");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(621, 346, 150, 30);

        jLabel8.setFont(new Font("Berlin Sans FB", Font.PLAIN, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Username");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(621, 143, 150, 30);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(520, 461, 320, 20);
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(520, 243, 320, 20);

        btnSignUp.setFont(new Font("Berlin Sans FB", Font.PLAIN, 26)); // NOI18N
        btnSignUp.setForeground(new java.awt.Color(255, 255, 255));
        btnSignUp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnSignUp.setText("Login");
        getContentPane().add(btnSignUp);
        btnSignUp.setBounds(583, 540, 150, 40);

        inpUsername.setFont(new java.awt.Font("Berlin Sans FB", 0, 15)); // NOI18N
        inpUsername.setForeground(new java.awt.Color(255, 255, 255));
        inpUsername.setBorder(null);
        getContentPane().add(inpUsername);
        inpUsername.setBounds(520, 183, 320, 50);

        inpPassword.setFont(new java.awt.Font("Berlin Sans FB", 0, 15)); // NOI18N
        inpPassword.setForeground(new java.awt.Color(255, 255, 255));
        inpPassword.setText("jPasswordField1");
        inpPassword.setBorder(null);
        getContentPane().add(inpPassword);
        inpPassword.setBounds(520, 401, 320, 50);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        //jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btnsignUp.png"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(490, 540, 150, 40);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        //jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btnLoginSwitch.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(730, 30, 140, 50);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        //jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btnSignUpSwitch.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(660, 30, 140, 50);

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB", 0, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        //this place
        getContentPane().add(jLabel1);
        jLabel1.setBounds(140, 130, 240, 50);

        rightPanel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        //rightPanel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/rightPanel.png"))); // NOI18N
        getContentPane().add(rightPanel);
        rightPanel.setBounds(430, 26, 515, 598);

        leftPanel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        //leftPanel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/leftPanelBack.png"))); // NOI18N
        getContentPane().add(leftPanel);
        leftPanel.setBounds(-70, 0, 565, 660);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnSignUp;
    private javax.swing.JPasswordField inpPassword;
    private javax.swing.JTextField inpUsername;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel leftPanel;
    private javax.swing.JLabel rightPanel;
    private JButton btnNewButton_2;
}